### ISSUE TITLE
Help Center

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#104]
**Description**

We need a help button to show features information, like how to create checks, how to create integration, how to connect integration with checks, how to create status pages, etc...

The button need to be always visible on the UI.

---

**Ideas**

![Image](https://user-images.githubusercontent.com/35310226/239398990-5df7a4c3-505b-43bd-b214-ca526e27ac4d.png)

---

**TO-DO**
- [x] Mobile design 
- [x] Skeleton loading for videos
- [x] Validate if the onboarding process already done
- [ ] Added meta property to the routers to show only on the selected pages or routers
- [x] Integrate external service to use in the Contact form
- [x] Create demonstration videos for each sub item of the menu
    ```
    2. Creating Checks
        * Setting up service targets ✅
        * Configuring check intervals ✅
        * Specifying timezone for each check✅
    3. Integrations
        * Adding Discord integration ✅
        * Setting up Email notifications ✅
        * Configuring Slack integration ✅
        * Enabling Telegram alerts ✅
        * Managing WhatsApp notifications ✅
        * Adding integrations to checks ✅
    4. Status Pages
        * Creating a dynamic dashboard ✅
        * Sharing information with teams ✅
    5. Log History
        * Tracking uptime and response times ✅
    6. Timezone Configuration
        * Managing general timezones ✅
    7. FAQs
        * Frequently asked questions ✅
    ```

**Comment by itsalb3rt** [comment]
Created the **Help Center** component

![image](https://github.com/ta-vivo/ta-vivo/assets/35310226/60e12d08-21d4-4369-a0ef-d58e1b47ac44)
