### ISSUE TITLE
In-app Metrics

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo#80]
**Description**

We need to implement in-app metrics, for example the average time of response from checks, downtimes per week, month and years.

**TO-DO**

- [x] Add the response time on the logs history
- [x] Add average time on the check index
- [x] Added up time on logs

**Before Close**
- [x] Merge the API [branch](https://github.com/ta-vivo/ta-vivo-api/tree/80-in-app-metrics)
- [x] Merge the frontend [branch](https://github.com/ta-vivo/ta-vivo/tree/80-in-app-metrics)

**Comment by itsalb3rt** [comment]
This issue is used to integrate new in-app metrics.
